@startuml Admin
left to right direction
package "Administrador"{
'Creating Actors
actor Administrador as A
actor Operador as U
' actor Usuario as Us
rectangle "Sistema"{
    usecase "CUP-1: Registrar usuarios" as 6
    usecase "CUP-2: Registrar sujeto" as 16   
    usecase "CUP-3: Registrar especies" as 7    
    usecase "CUP-4: Agregar rasgos de la especie a crear" as 8    
    usecase "CUI-2: Registrar un nuevo usuario" as 17   
}
A--> 6
A--> 7
7<--U
A--> 8
8<--U
A-->16
16<--U
17 <-- A
U --> 17
}